apiVersion: v1
kind: Service
metadata:
  name: httpd-service-Koonce
  namespace: httpd-websvr
spec:
  type: NodePort
  selector:
    app: httpd_app_websvr
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-koonce
  namespace: httpd-websvr
  labels:
    app: httpd_app_koonce
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd_app_koonce
  template:
    metadata:
      labels:
        app: httpd_app_koonce
    spec:
      containers:
        - name: httpd-container-koonce
          image: httpd:latest
          ports:
            - containerPort: 80
